// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID               int32          `json:"id"`
	LoginName        string         `json:"loginName"`
	PasswordHash     string         `json:"passwordHash"`
	GoogleAuthSecret sql.NullString `json:"googleAuthSecret"`
	Email            string         `json:"email"`
	IsVerified       sql.NullBool   `json:"isVerified"`
	Scope            []string       `json:"scope"`
	CreatedAt        sql.NullTime   `json:"createdAt"`
	UpdatedAt        sql.NullTime   `json:"updatedAt"`
}
